### ISSUE TITLE
用rollup打包无法载入'lib/index'依赖

### ISSUE THREAD

**Issue by owlikesj** [kaola-fed/octoparse#1]
打包配置如下：
```js
// rollup.config.js
import commonjs from 'rollup-plugin-commonjs';

export default {
  input: 'index.js',
  output: {
    file: 'bundle.js',
    format: 'es'
  },
  plugins: [ commonjs() ]
};
```

然后执行命令 `rollup --config rollup.config.js`

得到bundle.js文件如下：
```js
var octoParse = require('./lib/index').default;

exports.octoParse = octoParse;

export default octoParse;
```

原因可能是 index.js 文件混用commonjs和ESM语法，导致rollup无法提取依赖

**Comment by stevenBZ** [comment]
你好, 0.3.2版本已经修复了语法混用的问题，谢谢指正

**Comment by owlikesj** [comment]
> 你好, 0.3.2版本已经修复了语法混用的问题，谢谢指正

现在0.3.2版本，不支持 @megalo/vhtml-plugin 的如下导入方式了：
```js
const octoparse = require('octoparse').default
```
https://github.com/megalojs/megalo-vhtml-plugin/blob/master/index.js

**Comment by elcarim5efil** [comment]
`@megalo/vhtml-plugin@0.1.2` 统一用 commonjs 引用了。
`src` 目录可以提供到生产，但是 `package.json` 里面 `module` 不能配置成 `src/index.js`，否则引用时又会变成 `esmodule` 的引用方式。
