### ISSUE TITLE
<span>标签里面的文字 两边被自动加上了换行或空格

### ISSUE THREAD

**Issue by lazydan** [kaola-fed/octoparse#8]
<span>标签里面的文字 两边被自动加上了换行或空格导致行高很高
强制设置white-space:nowrap; 会单行正常, 但无法适用于多行内容

而且内部文字中  左边加6个换行, 右边加4个  导致文字偏右

**Comment by lazydan** [comment]
src/platform/wechat/index.wxml
是这里的模版, 因为格式化换行了, 导致span解析后内部文字两边有 换行+空格 
```
<template name="WxTextView">
    <view class="WxTextView octoParse-inline" style="{{item.styleStr}}">
      {{item.text}}
    </view>
</template>
```

**Comment by zzy7584** [comment]
我也遇到同样的问题。我的解决办法是：把格式化去掉，去掉所有的空格换行。
1. 把 **src/platform/wechat/index.wxml**  里面的代码去格式化，用网上html压缩工具普通压缩下就好了，去掉所有的空格和换行。然后放到自己项目的一个目录下。我这里是src/asset/template/wechat
2.把**src/platform/wechat/index.wxss**同样放到自己项目的src/asset/template/wechat下
3.配置webpack：在**megalo.config.js**中，configureWebpack 选项 ↓
`configureWebpack: config => {
    // 你可以在这里粗放的修改webpack的配置并返回
    config.target = createMegaloTarget({
      compiler,
      platform,
      htmlParse: {
        templateName: 'octoParse',
        src: path.resolve('src/asset/template/wechat/') // 这里注意下，只需要填目录就好
      }
    })
    console.log(config.target)
    return config
  },`

希望对你有帮助！

**Comment by zzy7584** [comment]
我也遇到同样的问题。我的解决办法是：把格式化去掉，去掉所有的空格换行。
1. 把 **src/platform/wechat/index.wxml**  里面的代码去格式化，用网上html压缩工具普通压缩下就好了，去掉所有的空格和换行。然后放到自己项目的一个目录下。我这里是src/asset/template/wechat
2. 把**src/platform/wechat/index.wxss**同样放到自己项目的src/asset/template/wechat下
3. 配置webpack：在**megalo.config.js**中，configureWebpack 选项 ↓
```
const compiler = require('@megalo/template-compiler')
const createMegaloTarget = require('@megalo/target')
const platform = 'wechat'
const path = require('path')

configureWebpack: config => {
    // 你可以在这里粗放的修改webpack的配置并返回
    config.target = createMegaloTarget({
      compiler,
      platform,
      htmlParse: {
        templateName: 'octoParse',
        src: path.resolve('src/asset/template/wechat/') // 这里注意下，只需要填目录就好
      }
    })
    console.log(config.target)
    return config
  },
```
希望对你有帮助！

**Comment by zzy7584** [comment]
我也遇到同样的问题。我的解决办法是：把格式化去掉，去掉所有的空格换行。
1. 把 **src/platform/wechat/index.wxml**  里面的代码去格式化，用网上html压缩工具普通压缩下就好了，去掉所有的空格和换行。然后放到自己项目的一个目录下。我这里是src/asset/template/wechat
2. 把**src/platform/wechat/index.wxss**同样放到自己项目的src/asset/template/wechat下
3. 配置webpack：在**megalo.config.js**中，configureWebpack 选项 ↓
```
const compiler = require('@megalo/template-compiler')
const createMegaloTarget = require('@megalo/target')
const platform = 'wechat'
const path = require('path')

configureWebpack: config => {
    // 你可以在这里粗放的修改webpack的配置并返回
    config.target = createMegaloTarget({
      compiler,
      platform,
      htmlParse: {
        templateName: 'octoParse',
        src: path.resolve('src/asset/template/wechat/') // 这里注意下，只需要填目录就好
      }
    })
    console.log(config.target)
    return config
  },
```
希望对你有帮助！

**Comment by lazydan** [comment]
@zzy7584 当时已找到该解决办法, 但同样感谢
